### ISSUE TITLE
redrock is stuck if LinAlgError: Singular matrix

### ISSUE THREAD

**Issue by londumas** [desihub/redrock#108]
In `py/redrock/_zscan.py` at line `zcoeff[:] = np.linalg.solve(M, y)` if `M` is not positive definite the code gives this error, continues with the different fit but then gets stuck at 90%:

```
MP calc_zchi2: Traceback (most recent call last):
MP calc_zchi2:   File "<me>/Programs/desi/code/redrock/py/redrock/zscan.py", line 145, in _mp_calc_zchi2
    progress=qprog)
MP calc_zchi2:   File "<me>/Programs/desi/code/redrock/py/redrock/zscan.py", line 123, in calc_zchi2
    weights, flux, wflux, dtemplate.local.data[i])
MP calc_zchi2:   File "<me>/Programs/desi/code/redrock/py/redrock/zscan.py", line 76, in calc_zchi2_one
    zchi2 = _zchi2_one(Tb, weights, flux, wflux, zcoeff)
MP calc_zchi2:   File "<me>/Programs/desi/code/redrock/py/redrock/_zscan.py", line 31, in _zchi2_one
    zcoeff[:] = np.linalg.solve(M, y)
MP calc_zchi2:   File "<me>/.local/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 375, in solve
    r = gufunc(a, b, signature=signature, extobj=extobj)
MP calc_zchi2:   File "<me>/.local/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 90, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
MP calc_zchi2: LinAlgError: Singular matrix
```

To test, send:
```
rrboss --spplate /uufs/chpc.utah.edu/common/home/sdss07/ebosswork/eboss/spectro/redux/v5_10_9/10432/spPlate-10432-58136.fits
 --zbest zbest-10432-58136.fits --output rrdetail-10432-58136.h5
 --ntargets 1 --mintarget 479
```
i.e. this issue is with plate, mjd, fiber = 10432, 58136, 483

**Comment by londumas** [comment]
One of the object giving such an error (plate, mjd, fiber = 10432, 58136, 483) has only 12 valid pixels.

**Comment by londumas** [comment]
A simple solution is to do a try/except:
```
    try:
        zcoeff[:] = np.linalg.solve(M, y)
    except:
        return -9999.
```
then set one of the ZWARNINGFLAG. What do you think @sbailey?
