### ISSUE TITLE
Travis problems with h5py and astropy

### ISSUE THREAD

**Issue by sbailey** [desihub/redrock#125]
The versions of astropy and h5py installed for the Travis tests appear to be incompatible, resulting in errors like
```
======================================================================
ERROR: test_zscan_io (redrock.test.test_io.TestIO)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/desihub/redrock/py/redrock/test/test_io.py", line 76, in test_zscan_io
    write_zscan(self.testfile, zscan1, zfit1)
  File "/home/travis/build/desihub/redrock/py/redrock/results.py", line 51, in write_zscan
    zbest.write(filename, path='zbest', format='hdf5')
  File "/home/travis/miniconda/envs/test/lib/python3.5/site-packages/astropy/table/table.py", line 2467, in write
    io_registry.write(self, *args, **kwargs)
  File "/home/travis/miniconda/envs/test/lib/python3.5/site-packages/astropy/io/registry.py", line 518, in write
    writer(data, *args, **kwargs)
  File "/home/travis/miniconda/envs/test/lib/python3.5/site-packages/astropy/io/misc/hdf5.py", line 214, in write_table_hdf5
    if isinstance(output, (h5py.highlevel.File, h5py.highlevel.Group)):
AttributeError: module 'h5py' has no attribute 'highlevel'
```
This is impacting multiple open PRs.  We need to fix the Travis config and then merge, rebase, or apply that fix by hand to each of the PR branches.

**Comment by weaverba137** [comment]
I think you really need to move to Astropy 2.  I'm not at all surprised that Astropy 1 is incompatible with h5py.

**Comment by weaverba137** [comment]
I'm working on a .travis.yml update for this.
