### ISSUE TITLE
Writing files is broken with 20180709-1.2.6-spec

### ISSUE THREAD

**Issue by londumas** [desihub/redrock#151]
When loading libraries from `/global/common/software/desi/edison/desiconda/20180709-1.2.6-spec`,
redrock crashes when writing the output files.
This issue is not there when using `/global/common/software/desi/${NERSC_HOST}/desiconda/20170920-1.2.0-spec/modulefiles/` 

```
Proc 0: Traceback (most recent call last):
Proc 0:   File "$HOME/Programs/desi/code/redrock/py/redrock/external/desi.py", line 624, in rrdesi
    write_zscan(args.output, scandata, zfit, clobber=True)
Proc 0:   File "$HOME/Programs/desi/code/redrock/py/redrock/results.py", line 51, in write_zscan
    zbest.write(filename, path='zbest', format='hdf5')
Proc 0:   File "/global/common/software/desi/edison/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/astropy/table/table.py", line 2548, in write
    io_registry.write(self, *args, **kwargs)
Proc 0:   File "/global/common/software/desi/edison/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/astropy/io/registry.py", line 581, in write
    writer(data, *args, **kwargs)
Proc 0:   File "/global/common/software/desi/edison/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/astropy/io/misc/hdf5.py", line 239, in write_table_hdf5
    f = h5py.File(output, 'a' if append else 'w')
Proc 0:   File "/global/common/software/desi/edison/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/h5py/_hl/files.py", line 312, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
Proc 0:   File "/global/common/software/desi/edison/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/h5py/_hl/files.py", line 148, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
Proc 0:   File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
Proc 0:   File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
Proc 0:   File "h5py/h5f.pyx", line 98, in h5py.h5f.create
Proc 0: OSError: Unable to create file (unable to lock file, errno = 524, error message = 'Unknown error 524')

Rank 0 [Wed Sep 12 08:08:24 2018] [c0-0c0s3n0] application called MPI_Abort(MPI_COMM_WORLD, 0) - process 0
srun: error: nid00012: task 0: Aborted
srun: Terminating job step 10689692.0
slurmstepd: error: *** STEP 10689692.0 ON nid00012 CANCELLED AT 2018-09-12T08:08:24 ***
srun: error: nid00012: tasks 1-7: Terminated
srun: Force Terminated job step 10689692.0
```

**Comment by londumas** [comment]
ok, thanks @sbailey
