### ISSUE TITLE
fix cosmics masking

### ISSUE THREAD

**Issue by sbailey** [desihub/redrock#188]
```
srun -N 1 -n 32 -c 2 rrdesi_mpi -z zbest-spectra-nsig4-0.fits --cosmics-nsig 4 \
    /global/cfs/cdirs/desi/spectro/redux/blanc/tiles/80608/20201216/spectra-0-80608-20201216.fits
```
crashes with
```
Proc 27: Traceback (most recent call last):
Proc 27:   File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/redrock/0.14.5/lib/python3.8/site-packages/redrock-0.14.5-py3.8.egg/redrock/external/desi.py", line 600, in rrdesi
    targets = DistTargetsDESI(args.infiles, coadd=(not args.allspec),
Proc 27:   File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/redrock/0.14.5/lib/python3.8/site-packages/redrock-0.14.5-py3.8.egg/redrock/external/desi.py", line 413, in __init__
    t.compute_coadd(cache_Rcsr,cosmics_nsig=self.cosmics_nsig)
Proc 27:   File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/redrock/0.14.5/lib/python3.8/site-packages/redrock-0.14.5-py3.8.egg/redrock/targets.py", line 179, in compute_coadd
    tflux[bad] = np.interp(wave[bad],wave[good],s.flux[good])
Proc 27:   File "<__array_function__ internals>", line 5, in interp
Proc 27:   File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/conda/lib/python3.8/site-packages/numpy/lib/function_base.py", line 1423, in interp
    return interp_func(x, xp, fp, left, right)
Proc 27: ValueError: array of sample points is empty
```
This might be the same problem fixed in desihub/desispec#1113 for desi_coadd_spectra cosmics masking, but I haven't checked.

**Comment by moustakas** [comment]
This ticket is more than three years old and doesn't seem to be an issue anymore; closing.
