### ISSUE TITLE
Error while running redrock in mock spectra

### ISSUE THREAD

**Issue by LuzGarciaP** [desihub/redrock#205]
When trying to run redrock on a small set of mocks located here: /global/cscratch1/sd/alxogm/BAL_mocks

I'm getting this error:
Traceback (most recent call last):
File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/code/redrock/master/bin/rrdesi", line 9, in
desi.rrdesi(comm=None)
File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/code/redrock/master/py/redrock/external/desi.py", line 804, in rrdesi
raise err
File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/code/redrock/master/py/redrock/external/desi.py", line 695, in rrdesi
targets = DistTargetsDESI(args.infiles, coadd=(not args.allspec),
File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/code/redrock/master/py/redrock/external/desi.py", line 219, in init
scores = encode_table(Table(hdus["SCORES"].data,
File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/conda/lib/python3.9/site-packages/astropy/io/fits/hdu/hdulist.py", line 323, in getitem
self._positive_index_of(key))
File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/conda/lib/python3.9/site-packages/astropy/io/fits/hdu/hdulist.py", line 780, in _positive_index_of
index = self.index_of(key)
File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/conda/lib/python3.9/site-packages/astropy/io/fits/hdu/hdulist.py", line 761, in index_of
raise KeyError(f'Extension {key!r} not found.')
KeyError: "Extension 'SCORES' not found."

Would it be possible to make SCORES an optional HDU again, please?

Best regards,
Luz García

**Comment by alxogm** [comment]
If redrock expects to have the resolution matrix always present we can re-run the mock Luz is using to include it.

**Comment by sbailey** [comment]
FWIW, I think rrdesi should not *require* SCORES or TNSR2 values, but it should require resolution matrix data and the sims should provide that.  Since the full resolution matrix format is large and probably overkill for fast sims, a compromise could be to define a Gaussian sigma (or FWHM) vs. wavelength HDU, and update redrock to support converting that into a resolution matrix to use.

**Comment by moustakas** [comment]
@LuzGarciaP @alxogm, I'm going to close this ticket as resolved, but please feel free to reopen (or open a new one) if this is still an issue.
