### ISSUE TITLE
assert 'COADD_NUMEXP' not in tmpfmap.dtype.names

### ISSUE THREAD

**Issue by forero** [desihub/redrock#212]
I am finding the following error while trying to update the notebooks in the desihub/tutorials repo to run under kernel 22.2 

```
zbest.coadd.fits
Running on a NERSC login node- reducing number of processes to 4
Running with 4 processes
Loading targets...
--- Process 0 raised an exception ---
Proc 0: Traceback (most recent call last):
Proc 0:   File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/code/redrock/0.15.4/lib/python3.9/site-packages/redrock/external/desi.py", line 695, in rrdesi
    targets = DistTargetsDESI(args.infiles, coadd=(not args.allspec),
Proc 0:   File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/code/redrock/0.15.4/lib/python3.9/site-packages/redrock/external/desi.py", line 210, in __init__
    assert 'COADD_NUMEXP' not in tmpfmap.dtype.names
Proc 0: AssertionError

Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/code/redrock/0.15.4/bin/rrdesi", line 9, in <module>
    desi.rrdesi(comm=None)
  File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/code/redrock/0.15.4/lib/python3.9/site-packages/redrock/external/desi.py", line 804, in rrdesi
    raise err
  File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/code/redrock/0.15.4/lib/python3.9/site-packages/redrock/external/desi.py", line 695, in rrdesi
    targets = DistTargetsDESI(args.infiles, coadd=(not args.allspec),
  File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/code/redrock/0.15.4/lib/python3.9/site-packages/redrock/external/desi.py", line 210, in __init__
    assert 'COADD_NUMEXP' not in tmpfmap.dtype.names
AssertionError
```

What is the best way to solve that problem?

Here is the notebook https://github.com/desihub/tutorials/blob/edb2d45202c874bc601bcf699321c56fcfe71fb2/Dec2020/galaxies/fitting_redshifts.ipynb

**Comment by forero** [comment]
@sbailey @akremin : do you have any idea on how to proceed in this case?

**Comment by moustakas** [comment]
@forero I don't think this is an issue in any of the more recent software releases, so I think we just need to update that tutorial; closing.
