### ISSUE TITLE
rrdesi+gpu (non-MPI) broken

### ISSUE THREAD

**Issue by sbailey** [desihub/redrock#223]
rrdesi in non-MPI mode is broken when requesting GPUs.  It appears to be a code flow bug rather than some fundamental incompatibility between multiprocessing + GPUs.

```
cd $CFS/desi/spectro/redux/fuji/tiles/cumulative/100/20210505
rrdesi -i coadd-0-100-thru20210505.fits -o $SCRATCH/blat.fits --gpu --max-gpuprocs 4
...
Read and broadcast of 11 templates: 0.0 seconds
--- Process 0 raised an exception ---
Proc 0: Traceback (most recent call last):
Proc 0:   File "/global/common/software/desi/perlmutter/desiconda/20220119-2.0.1/code/redrock/main/py/redrock/external/desi.py", line 779, in rrdesi
    dtemplates = load_dist_templates(dwave, templates=args.templates,
Proc 0:   File "/global/common/software/desi/perlmutter/desiconda/20220119-2.0.1/code/redrock/main/py/redrock/templates.py", line 501, in load_dist_templates
    dtemplate = ReDistTemplate(t, dwave, mp_procs=mp_procs, comm=comm)
Proc 0:   File "/global/common/software/desi/perlmutter/desiconda/20220119-2.0.1/code/redrock/main/py/redrock/templates.py", line 408, in __init__
    raise NotImplementedError("ReDistTemplate not implemented for non-MPI")
Proc 0: NotImplementedError: ReDistTemplate not implemented for non-MPI

Traceback (most recent call last):
  File "/global/common/software/desi/perlmutter/desiconda/20220119-2.0.1/code/redrock/main/bin/rrdesi", line 10, in <module>
    desi.rrdesi(comm=None)
  File "/global/common/software/desi/perlmutter/desiconda/20220119-2.0.1/code/redrock/main/py/redrock/external/desi.py", line 868, in rrdesi
    raise err
  File "/global/common/software/desi/perlmutter/desiconda/20220119-2.0.1/code/redrock/main/py/redrock/external/desi.py", line 779, in rrdesi
    dtemplates = load_dist_templates(dwave, templates=args.templates,
  File "/global/common/software/desi/perlmutter/desiconda/20220119-2.0.1/code/redrock/main/py/redrock/templates.py", line 501, in load_dist_templates
    dtemplate = ReDistTemplate(t, dwave, mp_procs=mp_procs, comm=comm)
  File "/global/common/software/desi/perlmutter/desiconda/20220119-2.0.1/code/redrock/main/py/redrock/templates.py", line 408, in __init__
    raise NotImplementedError("ReDistTemplate not implemented for non-MPI")
NotImplementedError: ReDistTemplate not implemented for non-MPI
```

Running without GPUs works:
```
rrdesi -i coadd-0-100-thru20210505.fits -o $SCRATCH/blat.fits
```

MPI also works with GPUs
```
srun -n 64 -c 2 rrdesi_mpi -i coadd-0-100-thru20210505.fits -o $SCRATCH/blat.fits --gpu --max-gpuprocs 4
```

**Comment by craigwarner-ufastro** [comment]
Just wanted to note that the ReDistTemplate will be deprecated after my PR is merged since we no longer need to redistribute targets among the GPU and non-GPU nodes.  It does seem there may be other issues with multiprocessing and cupy initialization which I will look at but this particular one will go away.

**Comment by moustakas** [comment]
I don't believe this is still an issue with more recent versions; closing.
