### ISSUE TITLE
redrock on a laptop no longer works

### ISSUE THREAD

**Issue by moustakas** [desihub/redrock#251]
For local development work it would be very helpful to be able to run `Redrock` on a laptop (in my case a circa-2021 Apple M1 Pro), but recent versions of the code no longer work.

E.g., in a clean conda environment and with a local copy of `$CFS/desi/spectro/redux/fuji/tiles/cumulative/100/20210505/coadd-0-100-thru20210505.fits`, I get the error log below. (Note: the `numba` deprecation warning seems to impact not just `redrock`, but also `desispec` and likely other repositories.)

```
rrdesi -i coadd-0-100-thru20210505.fits -o rr.fits

/Users/ioannis/code/desihub/redrock/py/redrock/rebin.py:126: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit
/Users/ioannis/code/desihub/redrock/py/redrock/rebin.py:178: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit
Running with 5 processes
WARNING:  using multiprocessing, but the OMP_NUM_THREADS
WARNING:  environment variable is not set- your system may
WARNING:  be oversubscribed.
Loading targets...
Read and distribution of 500 targets: 1.1 seconds
DEBUG: Read templates from /Users/ioannis/code/desihub/redrock-templates
DEBUG: Using default redshift range -0.0050-1.6997 for rrtemplate-galaxy.fits
DEBUG: Using redshift range 1.4000-6.9930 for rrtemplate-qso-HIZ.fits
DEBUG: Using redshift range 0.0500-1.5983 for rrtemplate-qso-LOZ.fits
DEBUG: Using default redshift range -0.0020-0.0020 for rrtemplate-star-A.fits
DEBUG: Using default redshift range -0.0020-0.0020 for rrtemplate-star-B.fits
DEBUG: Using default redshift range -0.0020-0.0020 for rrtemplate-star-CV.fits
DEBUG: Using default redshift range -0.0020-0.0020 for rrtemplate-star-F.fits
DEBUG: Using default redshift range -0.0020-0.0020 for rrtemplate-star-G.fits
DEBUG: Using default redshift range -0.0020-0.0020 for rrtemplate-star-K.fits
DEBUG: Using default redshift range -0.0020-0.0020 for rrtemplate-star-M.fits
DEBUG: Using default redshift range -0.0020-0.0020 for rrtemplate-star-WD.fits
Read and broadcast of 11 templates: 0.0 seconds
Creating GPU context: 0.0 seconds
Rebinning templates: 3.6 seconds
Computing redshifts
  Scanning redshifts for template GALAXY
--- Process 0 raised an exception ---
Proc 0: Traceback (most recent call last):
Proc 0:   File "/Users/ioannis/code/desihub/redrock/py/redrock/external/desi.py", line 823, in rrdesi
Proc 0:   File "/Users/ioannis/code/desihub/redrock/py/redrock/zfind.py", line 273, in zfind
Proc 0:   File "/Users/ioannis/code/desihub/redrock/py/redrock/zscan.py", line 905, in calc_zchi2_targets
Proc 0:   File "/Users/ioannis/code/desihub/redrock/py/redrock/targets.py", line 285, in sharedmem_pack
Proc 0:   File "/Users/ioannis/code/desihub/redrock/py/redrock/targets.py", line 101, in sharedmem_pack
Proc 0:   File "/Users/ioannis/code/desihub/redrock/py/redrock/utils.py", line 172, in mp_array
Proc 0:   File "/opt/homebrew/Caskroom/miniforge/base/envs/desi/lib/python3.11/multiprocessing/context.py", line 130, in RawArray
Proc 0:   File "/opt/homebrew/Caskroom/miniforge/base/envs/desi/lib/python3.11/multiprocessing/sharedctypes.py", line 66, in RawArray
Proc 0:   File "/opt/homebrew/Caskroom/miniforge/base/envs/desi/lib/python3.11/multiprocessing/sharedctypes.py", line 41, in _new_value
Proc 0:   File "/opt/homebrew/Caskroom/miniforge/base/envs/desi/lib/python3.11/multiprocessing/heap.py", line 331, in __init__
Proc 0:   File "/opt/homebrew/Caskroom/miniforge/base/envs/desi/lib/python3.11/multiprocessing/heap.py", line 309, in malloc
Proc 0:   File "/opt/homebrew/Caskroom/miniforge/base/envs/desi/lib/python3.11/multiprocessing/heap.py", line 192, in _malloc
Proc 0:   File "/opt/homebrew/Caskroom/miniforge/base/envs/desi/lib/python3.11/multiprocessing/heap.py", line 166, in _new_arena
Proc 0:   File "/opt/homebrew/Caskroom/miniforge/base/envs/desi/lib/python3.11/multiprocessing/heap.py", line 89, in __init__
Proc 0: OSError: [Errno 24] Too many open files

Traceback (most recent call last):
  File "/Users/ioannis/code/desihub/redrock/bin/rrdesi", line 10, in <module>
  File "/Users/ioannis/code/desihub/redrock/py/redrock/external/desi.py", line 904, in rrdesi
  File "/Users/ioannis/code/desihub/redrock/py/redrock/external/desi.py", line 823, in rrdesi
  File "/Users/ioannis/code/desihub/redrock/py/redrock/zfind.py", line 273, in zfind
  File "/Users/ioannis/code/desihub/redrock/py/redrock/zscan.py", line 905, in calc_zchi2_targets
  File "/Users/ioannis/code/desihub/redrock/py/redrock/targets.py", line 285, in sharedmem_pack
  File "/Users/ioannis/code/desihub/redrock/py/redrock/targets.py", line 101, in sharedmem_pack
  File "/Users/ioannis/code/desihub/redrock/py/redrock/utils.py", line 172, in mp_array
  File "/opt/homebrew/Caskroom/miniforge/base/envs/desi/lib/python3.11/multiprocessing/context.py", line 130, in RawArray
  File "/opt/homebrew/Caskroom/miniforge/base/envs/desi/lib/python3.11/multiprocessing/sharedctypes.py", line 66, in RawArray
  File "/opt/homebrew/Caskroom/miniforge/base/envs/desi/lib/python3.11/multiprocessing/sharedctypes.py", line 41, in _new_value
  File "/opt/homebrew/Caskroom/miniforge/base/envs/desi/lib/python3.11/multiprocessing/heap.py", line 331, in __init__
  File "/opt/homebrew/Caskroom/miniforge/base/envs/desi/lib/python3.11/multiprocessing/heap.py", line 309, in malloc
  File "/opt/homebrew/Caskroom/miniforge/base/envs/desi/lib/python3.11/multiprocessing/heap.py", line 192, in _malloc
  File "/opt/homebrew/Caskroom/miniforge/base/envs/desi/lib/python3.11/multiprocessing/heap.py", line 166, in _new_arena
  File "/opt/homebrew/Caskroom/miniforge/base/envs/desi/lib/python3.11/multiprocessing/heap.py", line 89, in __init__
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/desi/lib/python3.11/multiprocessing/util.py", line 300, in _run_finalizers
  File "/opt/homebrew/Caskroom/miniforge/base/envs/desi/lib/python3.11/multiprocessing/util.py", line 224, in __call__
  File "/opt/homebrew/Caskroom/miniforge/base/envs/desi/lib/python3.11/multiprocessing/util.py", line 133, in _remove_temp_dir
  File "/opt/homebrew/Caskroom/miniforge/base/envs/desi/lib/python3.11/shutil.py", line 728, in rmtree
  File "/opt/homebrew/Caskroom/miniforge/base/envs/desi/lib/python3.11/shutil.py", line 725, in rmtree
OSError: [Errno 24] Too many open files: '/var/folders/r5/35zd2wl1281fzg88q92g76sc0000gq/T/pymp-sxn9tv_9'
```

**Comment by sbailey** [comment]
@craigwarner-ufastro could you take a look at this?  I suspect it is a side effect of the recent refactoring to increase GPU support but broke the multiprocessing path when run on files with many targets.  If you are unable to reproduce this, please also post that and we'll expanding the testing pool and sort it out.  Thanks.

**Comment by craigwarner-ufastro** [comment]
It looks to me like the error is coming from 
```                tg.sharedmem_pack()```
specifically
```                self.Rcsr_data = mp_array(self._Rcsr.data)```
so I don't think its anything related to GPU refactoring - it looks to me like a setting in the Linux install on the Macbook that is limiting the number of open files at once and conflicting with the large number of targets.

My suggestion is to check
`ulimit -n`
and see what the upper limit of open file descriptors is and try increasing it (e.g. if it is 1024, try increasing to 2048 via `ulimit -n 2048`) and see if that fixes the issue.  Cheers.

**Comment by moustakas** [comment]
Thanks @craigwarner-ufastro, setting `ulimit -n 2048` (mine was set to 256) resolved this issue for me.
