### ISSUE TITLE
fix redrock integration with desiInstall

### ISSUE THREAD

**Issue by sbailey** [desihub/redrock#28]
Fix etc/redrock.modules and possibly desiInstall so that "desiInstall redrock {version}" will work at NERSC.  Currently it installs a modules file that points to /project instead of /usr/common and doesn't install the templates.

Consider whether the templates should always be installed as a separate product, or installed into redrock itself.  Templates are kept as a separate github repo to keep big files away from the code, but redrock supports them either being installed into redrock/templates, or in some other location while setting the `$RR_TEMPLATES_DIR` environment variable.

For the purposes of today, I will install and cleanup redrock by hand at NERSC.

**Comment by sbailey** [comment]
Further info: the installation procedure replaced `bin/rrdesi` with the following:
```python
#!/global/common/cori/contrib/desi/desiconda/20170613-1.1.4-spectro/code/desiconda/20170613-1.1.4-spectro_conda/bin/python
# EASY-INSTALL-SCRIPT: 'redrock==0.5.0','rrdesi'
__requires__ = 'redrock==0.5.0'
__import__('pkg_resources').run_script('redrock==0.5.0', 'rrdesi')
```
which fails with this message
```
Traceback (most recent call last):
  File "/global/common/cori/contrib/desi/desiconda/20170613-1.1.4-spectro/code/redrock/0.5.0/bin/rrdesi", line 4, in <module>
    __import__('pkg_resources').run_script('redrock==0.5.0', 'rrdesi')
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/global/common/cori/contrib/desi/desiconda/20170613-1.1.4-spectro/code/desiconda/20170613-1.1.4-spectro_conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 2985, in <module>
  File "/global/common/cori/contrib/desi/desiconda/20170613-1.1.4-spectro/code/desiconda/20170613-1.1.4-spectro_conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 2971, in _call_aside
  File "/global/common/cori/contrib/desi/desiconda/20170613-1.1.4-spectro/code/desiconda/20170613-1.1.4-spectro_conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 2998, in _initialize_master_working_set
  File "/global/common/cori/contrib/desi/desiconda/20170613-1.1.4-spectro/code/desiconda/20170613-1.1.4-spectro_conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 660, in _build_master
  File "/global/common/cori/contrib/desi/desiconda/20170613-1.1.4-spectro/code/desiconda/20170613-1.1.4-spectro_conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 968, in require
  File "/global/common/cori/contrib/desi/desiconda/20170613-1.1.4-spectro/code/desiconda/20170613-1.1.4-spectro_conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 854, in resolve
pkg_resources.DistributionNotFound: The 'redrock==0.5.0' distribution was not found and is required by the application
```
even though redrock 0.5.0 is visible to python:
```
<cori spectra-64> python -c "import redrock; print(redrock.__version__)"
0.5.0
```

Simply restoring `bin/rrdesi` to what it was in the first place fixes it:
```python
#!/usr/bin/env python

"""
Redrock for DESI
"""
from redrock.external import desi
desi.rrdesi()
```

That fixed the 0.5.0 install, but we still need to fix setup.py so that installing doesn't break the code.
