### ISSUE TITLE
rrboss is broken with `dimension mismatch`

### ISSUE THREAD

**Issue by londumas** [desihub/redrock#75]
The new master broke rrboss.
When running on NERSC:
```
rrboss  --spplate /project/projectdirs/cosmo/data/sdss/dr14/eboss/spectro/redux/v5_10_0/3615/spPlate-3615-55179.fits --zbest   zbest-3615-55179.fits  --output  rrdetail-3615-55179.h5
```
I get:
```
Running on a NERSC login node- reducing number of processes to 4
Running with 4 processes
Loading targets...
DEBUG: skipping plate,fid = 3615,796 (no data)
DEBUG: read /project/projectdirs/cosmo/data/sdss/dr14/eboss/spectro/redux/v5_10_0/3615/spPlate-3615-55179.fits 
Read of 999 targets: 39.3 seconds
Distribution of 999 targets: 0.0 seconds
DEBUG: Can't find redshift range info in template file /global/homes/h/hdumasde/Programs/desi/code/redrock/py/redrock/templates/rrtemplate-star-A.fits, using default values
DEBUG: Can't find redshift range info in template file /global/homes/h/hdumasde/Programs/desi/code/redrock/py/redrock/templates/rrtemplate-star-B.fits, using default values
DEBUG: Can't find redshift range info in template file /global/homes/h/hdumasde/Programs/desi/code/redrock/py/redrock/templates/rrtemplate-star-M.fits, using default values
DEBUG: Can't find redshift range info in template file /global/homes/h/hdumasde/Programs/desi/code/redrock/py/redrock/templates/rrtemplate-galaxy.fits, using default values
DEBUG: Can't find redshift range info in template file /global/homes/h/hdumasde/Programs/desi/code/redrock/py/redrock/templates/rrtemplate-star-F.fits, using default values
DEBUG: Can't find redshift range info in template file /global/homes/h/hdumasde/Programs/desi/code/redrock/py/redrock/templates/rrtemplate-qso.fits, using default values
DEBUG: Can't find redshift range info in template file /global/homes/h/hdumasde/Programs/desi/code/redrock/py/redrock/templates/rrtemplate-star-K.fits, using default values
DEBUG: Can't find redshift range info in template file /global/homes/h/hdumasde/Programs/desi/code/redrock/py/redrock/templates/rrtemplate-star-G.fits, using default values
Read and broadcast of 8 templates: 0.2 seconds
Rebinning templates: 13.0 seconds
Computing redshifts
  Scanning redshifts for template STAR:A
    Progress:   0 %
MP calc_zchi2: Traceback (most recent call last):
MP calc_zchi2:   File "/global/homes/h/hdumasde/Programs/desi/code/redrock/py/redrock/zscan.py", line 145, in _mp_calc_zchi2
    progress=qprog)
MP calc_zchi2:   File "/global/homes/h/hdumasde/Programs/desi/code/redrock/py/redrock/zscan.py", line 122, in calc_zchi2
    weights, flux, wflux, dtemplate.local.data[i])
MP calc_zchi2:   File "/global/homes/h/hdumasde/Programs/desi/code/redrock/py/redrock/zscan.py", line 73, in calc_zchi2_one
    Tb.append(s.Rcsr.dot(tdata[key]))
MP calc_zchi2:   File "/global/common/software/desi/cori/desiconda/20170920-1.2.0-spec/conda/lib/python3.6/site-packages/scipy/sparse/base.py", line 302, in dot
    return self * other
MP calc_zchi2:   File "/global/common/software/desi/cori/desiconda/20170920-1.2.0-spec/conda/lib/python3.6/site-packages/scipy/sparse/base.py", line 405, in __mul__
    raise ValueError('dimension mismatch')
MP calc_zchi2: ValueError: dimension mismatch
```

**Comment by tskisner** [comment]
That is strange- I tested it against plate 4444 with no trouble.  Will investigate this weekend.

**Comment by londumas** [comment]
I have just tested with `/project/projectdirs/cosmo/data/sdss/dr14/eboss/spectro/redux/v5_10_0/4444/spPlate-4444-55538.fits` and it doesn't work, i.e. I get the same error

**Comment by londumas** [comment]
With `-ntargets 1` on plate 4444 it works well. But without the argument, it doesn't work.
It might be liked to the fact that we loose one spectrum:
`DEBUG: skipping plate,fid = 4444,925 (no data)`

**Comment by tskisner** [comment]
Ok I just reproduced this on cori.  Since this plate worked with the refactor branch prior to rebasing against master, that operation must have introduced the problem.  Note that the rrboss_mpi entrypoint does not exhibit the error, so this is in the multiprocessing wrapper.  I'll track it down.

**Comment by tskisner** [comment]
I have fixed this problem, will open a PR shortly.
