### ISSUE TITLE
don't crash on NaN

### ISSUE THREAD

**Issue by sbailey** [desihub/redrock#98]
From PR #97 discussion: redrock currently fails if the input spectra have NaNs.  They shouldn't have NaNs in the first place, but even if they do we should just filter them out as if ivar=0 for those wavelengths.
```
rrdesi /global/cscratch1/sd/jguy/sim2017/redux/month5/spectra-64/59/5925/spectra-64-5925.fits -o rr-64-5925.h5 --zbest zbest-64-5925.fits --mp 32
...
/global/common/software/desi/users/jguy/redrock/py/redrock/zscan.py:44: RuntimeWarning: invalid value encountered in multiply
  wflux = weights * flux
    Finished in: 5.1 seconds
  Finding best fits for template GALAXY
MP calc_zchi2: Traceback (most recent call last):
MP calc_zchi2:   File "/global/common/software/desi/users/jguy/redrock/py/redrock/zfind.py", line 46, in _mp_fitz
    t.template, nminima=nminima)
MP calc_zchi2:   File "/global/common/software/desi/users/jguy/redrock/py/redrock/fitz.py", line 219, in fitz
    results = Table(results)
MP calc_zchi2:   File "/global/common/software/desi/cori/desiconda/20180130-1.2.4-spec/conda/lib/python3.6/site-packages/astropy/table
/table.py", line 392, in __init__
    init_func(data, names, dtype, n_cols, copy)
MP calc_zchi2:   File "/global/common/software/desi/cori/desiconda/20180130-1.2.4-spec/conda/lib/python3.6/site-packages/astropy/table
/table.py", line 663, in _init_from_list
    self._init_from_cols(cols)
MP calc_zchi2:   File "/global/common/software/desi/cori/desiconda/20180130-1.2.4-spec/conda/lib/python3.6/site-packages/astropy/table
/table.py", line 728, in _init_from_cols
    .format(lengths))
MP calc_zchi2: ValueError: Inconsistent data column lengths: set()

/global/common/software/desi/users/jguy/redrock/py/redrock/zscan.py:44: RuntimeWarning: invalid value encountered in multiply
  wflux = weights * flux
/global/common/software/desi/users/jguy/redrock/py/redrock/fitz.py:60: RuntimeWarning: invalid value encountered in less_equal
  ii = np.where(np.r_[True, x[1:]<=x[:-1]] & np.r_[x[:-1]<=x[1:], True])[0]
```

**Comment by londumas** [comment]
@sbailey, isn't that fixed?

**Comment by julienguy** [comment]
yes, it's fixed
